### ISSUE TITLE
'buffer_accessed' is not reset in __releasebuffer__

### ISSUE THREAD

**Issue by jelledevleeschouwer** [maierman/binbuffer#2]
Dear @maierman,

Thanks for the great article, I really enjoyed it.

I have one question though. In your final version of binbuffer you state in the comment on top:

> you'll see that the view_count and buffer_accessed are somewhat redundant and you could actually remove view_count entirely without changing any functionality.

But I've noticed that `buffer_accessed` is not actually reset in `__releasebuffer__`, is that intentional? Is that because the statement you made about `__releasebuffer__`:

> However, NumPy doesn’t respect this, and expects that buffers maintain their data even after calls to __releasebuffer__. So in our case, we don’t actually have to do anything here.

So indeed, in `__releasebuffer__`, the buffer isn't actually released. So in that case `buffer_accessed` may not actually be reset? Is that correct?

**Comment by jelledevleeschouwer** [comment]
Apologies, you answer my question in your comment on the declaration of `buffer_accessed` already:
```cython
cdef class SimpleBuffer:
    cdef:
        # ...
        bool buffer_accessed  # we need this because NumPy expects buffers to exist even after releasebuffer
```

**Comment by maierman** [comment]
Hi, 

Sorry for the late response here.  It seems like you resolved your question on your own though so nothing for me to do!.  

Like I said in my comments, last I saw, I think numpy calls releasebuffer, but then it is still holding onto a pointer to the buffer anyway even though it shouldn't be.   And because numpy holds onto the buffer, if you call np.frombuffer on one of our Cython buffers and then change the size, it may cause unpredictable behaviour in numpy since numpy won't know that you changed the size of the buffer.  So to protect against that, I added protection that prevents changing the buffer both when there are views open ( the intended usage for the protocol ) and also if the buffer has ever been accessed ( since that's currently necessary when using this with numpy )

You can see the numpy code by downloading the repo and searching for 'frombuffer'.  It's using the C-API directly rather than Cython but the calls will look familiar.

Glad you found this useful!
